### ISSUE TITLE
Battle Engine - Rhythm mechanics Checklist

### ISSUE THREAD

**Issue by Lamby777** [Lamby777/PETS-G#18]
Split off from #8 for better focus.

- [x] Load rhythm from serialized data (don't do that Xmarks crap again) #17 
- [x] Sync game to music #17
- [x] Tempo Shifts #17
- [ ] Clicks deal damage if on-time #17 
- [ ] Power chords (certain beats deal extra damage) 3af74e4
- [ ] Missed beats warn silently, while incorrect clicks give audio feedback

**Comment by Lamby777** [comment]
What if I just wrote a macro that generated stuff from Xmarks instead of loading from a file? :trollface:

**Comment by Lamby777** [comment]
MIDI rules. Attack stuff is gonna be put off for later after HP/enemy stats stuff is finished, so for now, everything I need is done. Closing.
