### ISSUE TITLE
Battle Engine Checklist

### ISSUE THREAD

**Issue by Lamby777** [Lamby777/PETS-G#8]
I'm not gonna bother starting work on this one til [the Rust bindings project for GDExtension becomes stable](https://github.com/godot-rust/gdext/issues/24). Just wanted to plan stuff out here and enumerate all the tasks to do when it eventually does become stable, though.

General
- [ ] Intro silence, don't allow clicking before music
- [ ] Allow modifying intro (for boss fights n stuff)
- [ ] Win screen with dialog box and rewards/etc
- [ ] Show name of track
- [ ] Show battle portrait of current character
- [ ] Switching characters
- [ ] Prevent character swap abuse (maybe a penalty? or a cooldown?)
- [ ] Status effects (think of poison, sleep deprivation, etc.)
- [ ] Character-specific permanent effects (weaknesses/strengths...? idk how to explain it)
- [ ] Using items
- [ ] Running away (needs further thought for implementation...)
- [ ] Enemy throws projectiles at player
- [ ] Enemy can use specializations in real-time
- [ ] UI info/warnings for enemy specializations
- [ ] Stats for player/enemy
- [ ] Weapons offset stats (there won't be "armor" in the usual sense. this is a deliberate decision)
- [ ] HP bar, takes up full space if char doesn't have ability with a mana bar
- [ ] Mana bar (BPP for PK, Ammo for firearms, Charge for railgun, etc.)
- [ ] Gain BPP by picking up specific item on board
- [ ] Add a way to override the algorithm for spawning BPP items (for boss fights, etc)

Combo system:
- [ ] Load rhythm from serialized data (don't do that Xmarks crap again)
- [ ] Sync game to music
- [ ] Clicks deal damage if on-time
- [ ] Power chords (certain beats deal extra damage)
- [ ] Missed beats warn silently, while incorrect clicks give audio feedback

Specializations for (playable?) characters:
- [ ] Psychokinesis (Ethan, Siva)
- [ ] Standard Firearms (Terra, Dylan)
- [ ] Extrasensory (Porky)
- [ ] InterSHELL CLI (Mira)
- [ ] Tech / Hacking (Mira, Leo, Juno)
- [ ] Railgun (Winthrus)
- [ ] Tricks & Confusion (Leo, Juno)

**Comment by Lamby777** [comment]
Starting work on this... maybe? :)

**Comment by Lamby777** [comment]
This is getting somewhat complicated, so I'll break it down into 3 separate issues for each section. REASONABLE goals, man.

**Comment by Lamby777** [comment]
Well, one complete in 7165e1f lol
The others will take a bit longer cuz the actual battle engine isn't made yet.

**Comment by Lamby777** [comment]
Idea for how running would work, taken from a comment in `src/battle/mod.rs`

"While running away, you won't be able to fight back, but once the countdown is over, you'll escape the fight."

**Comment by Lamby777** [comment]
> Idea: Rather than having some punishment for an arbitrarily "too frequent" pausing or whatever, the "default" state of battle could be a menu just like any other game, but the "attack" option puts you into the bullet hell mode for a minimum of X seconds, after which you can exit back to the menu if you wish, or continue fighting. This exit behavior could be disabled for special attacks or stuff like that so people can't cheese, but for the most part this seems like the best compromise.

Update: The default mode should be attack, and opening the menu doesn't actually make things easier for you, so you can only really do it when it's "calm" and there are relatively few attacks going on. Kinda realistic, too. You wouldn't eat a sandwich while being chased by a killer robot, right?

**Comment by Lamby777** [comment]
> Idea: Rather than having some punishment for an arbitrarily "too frequent" pausing or whatever, the "default" state of battle could be a menu just like any other game, but the "attack" option puts you into the bullet hell mode for a minimum of X seconds, after which you can exit back to the menu if you wish, or continue fighting. This exit behavior could be disabled for special attacks or stuff like that so people can't cheese, but for the most part this seems like the best compromise.

Thinking of completely overhauling the battle system actually... It'll be turn-based like EarthBound or Persona or whatever but after you pick a move, so does the enemy. The way it'll work is that you'll then dodge stuff while clicking to the beat like it currently works, until the enemy's attack is over. Your clicks will either deal pieces of damage or have a chance of inflicting a status effect, or whatever else the move you picked says it does to the enemy (or your team). This'll make the party system way easier, since you can control 1 and the other 3 will just take a randomized % of the hits as if they were dodging along with you IF the enemy's attack applied to them.

The original idea of fully live bullet-hell gameplay is nice, but kinda sucks ass for implementing meaningful dialogue or "skills" and other tactics stuff. This solution keeps that, and is the best of both worlds. Also doesn't feel too overcomplicated or clunky, at least on paper.
